// Few-shot examples: provide example texts for each category
export const fewShotExamples = {
  'system_configuration': [
    'Check the server status and uptime',
    'Is the system running properly?',
    'Monitor the infrastructure health and performance',
    'What is the uptime of the service?',
    "What's the current system health status?",
    'Check the logs for any errors or warnings',
    'How many users are currently online?',
    'Is the database alive and responding?',
    'Monitor the CPU and memory usage on production',
    'Restart the application server',
    'The LMS has been slow and students are reporting timeouts',
    'Review the error logs and verify database connection pool settings',
    'Check if CPU or memory is spiking during peak hours',
    'Confirm that the nightly backup jobs are completing successfully',
    'Scale up the infrastructure during high traffic periods',
    'Verify the cache hit ratio and Redis performance',
    'Audit the system metrics and server health',
    'Check the database replication status',
    'Monitor disk usage on the primary server',
    'Investigate infrastructure bottlenecks and latency issues',
    'Verify API gateway is not throttling legitimate traffic',
    'Check the deployment pipeline and CI/CD status',
    'Monitor network bandwidth and connection stability',
    'Review system configurations and environment variables',
    'Analyze server load balancing and auto-scaling settings',
    'Give me some suggestions to indexing the database for better performance'
  ],
  'data_analysis': [
    'Analyze the scores from class L01',
    'Show me statistics about student performance in this course',
    'What are the average grades?',
    'Generate a report on quiz results',
    'Compare performance across different classes',
    'What percentage of students passed the exam?',
    'Show me the grade distribution for this course',
    'Analyze the improvement trend over time',
    'Calculate the median score for the assignment',
    'Generate analytics dashboard for student progress',
    'Analyze how students performed in the last two assignments and summarize the trend',
    'I want the average, median, and distribution by score band',
    'Compare performance between sections A and B',
    'Flag any outliers and list students who dropped more than 10 points',
    'Show the pass rate and highlight classes with unusually low averages',
    'Calculate the standard deviation and percentile ranks',
    'Generate a summary of overall student performance this term',
    'Analyze which topics students struggled with most',
    'Show the grade trends over the past three months',
    'Identify students who are struggling and need intervention',
    'Compare completion rates year over year',
    'Generate a correlation analysis between quiz and exam scores',
    'Show the distribution of scores across all assignments',
    'Calculate average improvement rates per student cohort',
    'Analyze attendance patterns and their impact on performance'
  ],
  'quiz_creation': [
    'Create a quiz about mathematics',
    'Generate assessment questions for chapter 5',
    'Design a test for chapter 3',
    'Make practice questions about photosynthesis',
    'Design practice problems for calculus',
    'Create exercises for linear algebra',
    'Generate practice problems for students',
    'Make a test about chemistry',
    'Build assessment questions for physics',
    'Make a test about history of Vietnam',
    'Design a new assessment pack for our biology unit',
    'Create a quiz on cell division and genetics',
    'Add short-answer questions about DNA replication',
    'Give me higher-order questions that assess critical thinking rather than memorization',
    'Create a 20-question quiz on probability basics',
    'Add practice problems about conditional probability and Bayes theorem',
    'Build a mini-test for statistics covering mean, variance, and standard deviation',
    'Include an answer key for each part',
    'Generate multiple-choice questions with distractors',
    'Create a comprehensive exam with rubrics',
    'Design formative assessment questions for the midterm',
    'Build a quiz package covering limits, derivatives, and integrals',
    'Create application problems about optimization',
    'Generate conceptual questions that test intuition rather than computation',
    'Make practice exercises for the review session'
  ]
};
